### ISSUE TITLE
Missing event after latest update

### ISSUE THREAD

**Issue by KaIKuxy** [techchrism/valorant-autorecord#4]
```Found 56 events, missing: OnJsonApiEvent_chat_v4_presences``` keeps showing even if game is launched

**Comment by techchrism** [comment]
Does this still happen? I haven't observed this with the latest update

**Comment by lorinvzyl** [comment]
It used to happen to me as well, doesn't happen anymore from what I could see.

**Comment by techchrism** [comment]
I have encountered this error on the current `release-07.08-4-1007528`

The `OnJsonApiEvent_chat_v4_presences` is still triggering when listened to explicitly but it doesn't initially appear in the help endpoint.

I think the solution I'll implement is using the log to determine game readiness instead of waiting for events to appear in the help endpoint.

**Comment by techchrism** [comment]
The log readiness method seems to work. Here are the 5 events that were missing from the help endpoint until they were explicitly listened to: <https://gist.github.com/techchrism/7e7afc87d72adb76a212da03c9cd28f5>
